version: '3'
services:
  react-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 5173:5173
  quarkus-app:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./back/src/main/resources/import.sql:/usr/app/resources/import.sql  
    environment:
      - quarkus.datasource.db-kind=h2
      - quarkus.datasource.initial-sql=/usr/app/resources/import.sql
      - quarkus.datasource.devservices.init-script-path=/usr/app/resources/import.sql
      - quarkus.datasource.jdbc.url=jdbc:h2:mem:database=testdb;DB_CLOSE_DELAY=-1
      - quarkus.datasource.init.sql=/usr/app/resources/import.sql
      - quarkus.hibernate-orm.sql-load-script=import.sql
      - quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect
      - quarkus.hibernate-orm.database.generation=drop-and-create
      - quarkus.hibernate-orm.log.sql=true
      - quarkus.http.cors=true
      - quarkus.http.cors.origins=http://localhost:8080,http://localhost:3000,http://localhost:5173
      - quarkus.http.cors.methods=GET,POST,PUT,DELETE
      - quarkus.http.cors.headers=*
